app = "sistema-joyeria-adrian-tx-2024"
primary_region = "mad"

[build]

[env]
  NODE_ENV = "production"

[http_service]
  internal_port = 5001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
