services:
  - type: web
    name: sistema-joyeria
    env: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm run render-start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: NODE_OPTIONS
        value: "--max-old-space-size=512"
      - key: DB_PERSISTENCE
        value: "true"
      - key: DB_PATH
        value: "./server/database/jewelry_inventory.db"
    healthCheckPath: /api/health
    autoDeploy: true
    branch: main
